Proposition d'attelier pour `@codegouvfr/react-dsfr`
blue-hats/ateliers pull request #24
Opened 2022-11-12 22:18 UTC by garronej

2022-11-13 00:08 UTC, bzg commented on ateliers.org
> +- 🐸 (Bonus) Votre site actuel utilise [MUI](https://mui.org)? `react-dsfr` peut le DSFRifier avec un simple provider.
Il faudrait "org-ifier" ce lien, qui est resté en markdown.

2022-11-13 00:09 UTC, bzg requested changes
Juste un lien à corriger.

2022-11-14 14:56 UTC, merged

2022-11-14 14:56 UTC, bzg commented
Thanks!

2022-11-14 16:44 UTC, garronej commented
Merci a toi